/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        // TestCases tests = new TestCases(); // Initialize your test class

        // //TODO: call your test case functions one after other here

        // tests.testCase01();

        //END Tests

        // Start SearchAmzon on Google
         SearchAmazon tests = new SearchAmazon(); // Initialize your test class

        //TODO: call your test case functions one after other here

        tests.Search();

        //END SearchAmzon on Google

        //Start Count Hyperlinks on Bookmyshow
        CountHyperLink Ch = new CountHyperLink(); // Initialize your test class

        //TODO: call your test case functions one after other here

         Ch.count();        
         //End Count Hyperlinks on Bookmyshow        

         //Start post on linkedin
         PostOnLinkedIn pl = new PostOnLinkedIn(); // Initialize your test class

        //TODO: call your test case functions one after other here

         pl.Post_on_linkedin();        
         //End post on linkedin       

        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
