/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        // TestCases tests = new TestCases(); // Initialize your test class

        // //TODO: call your test case functions one after other here

        // tests.testCase01();

        //END Tests

        // Start SearchAmzon on Google
         SearchAmazon tests = new SearchAmazon(); // Initialize your test class
        // //TODO: call your test case functions one after other here
        tests.Search();
        tests.endTest();
        // //END SearchAmzon on Google

        // //Start Count Hyperlinks on Bookmyshow
        CountHyperLink Ch = new CountHyperLink(); // Initialize your test class
        // //TODO: call your test case functions one after other here
         Ch.count();        
         Ch.endTest();
         //End Count Hyperlinks on Bookmyshow        

         //Start post on linkedin
        //  PostOnLinkedIn pl = new PostOnLinkedIn(); // Initialize your test class

        // //TODO: call your test case functions one after other here

        //  pl.Post_on_linkedin();   
        // pl.endTest();     
         //End post on linkedin       

          // Start Print all text
         FrameText ft = new FrameText(); // Initialize your test class
        // //TODO: call your test case functions one after other here
         ft.Text();        
         ft.endTest();
         //End Print all text  

         // Start Window handle
         WindowHandle wh = new WindowHandle(); // Initialize your test class
        // //TODO: call your test case functions one after other here
         wh.Handle();
         wh.endTest();        
         //End Window handle

         // Start Window handle
         IMDB ir = new IMDB(); // Initialize your test class
        //TODO: call your test case functions one after other here
         ir.ImdbRatings();   
         ir.endTest();     
         //End Window handle

         // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
